[package]
name = "xbible_engine"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]

directories = "5.0"
fnv = "1.0.7"
isolang = "2.4.0"
roxmltree = "0.21.1"
uniffi = { version = "0.31.1", features = [
   "cli",
    "scaffolding-ffi-buffer-fns",
] }
regex = "1.12.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
zip = "8.6.0"
thiserror = "2.0.18"
chacha20poly1305 = "0.10.1"
image = {version = "0.25.10", default-features = false, features = ["png", "jpeg"] }
reqwest = {version = "0.13.4", features = [ "json", "stream", ] }
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread", "fs"] }
futures-util = { version = "0.3.32", features = ["alloc"] }
bytes = "1.11.1"
log = "0.4.33"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[build-dependencies]
bindgen = "0.72.1"
cmake = "0.1"
toml = "0.7"
pkg-config = "0.3"
